In [2]:
import torch
import numpy as np

In [4]:
t = torch.Tensor()
t

tensor([])

In [5]:
type(t)

torch.Tensor

In [8]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [10]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [13]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])
print(t1.dtype)
print(t2.dtype)

torch.int64
torch.float32


In [14]:
t1+t2

RuntimeError: expected type torch.FloatTensor but got torch.LongTensor

In [22]:
t2 = t1.cuda()
t2.device

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [23]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [35]:
t_constructor = torch.Tensor(data)
t_constructor

tensor([1., 2., 3.])

In [36]:
t_factory1 = torch.tensor(data)
t_factory1

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
t_factory2 = torch.as_tensor(data)
t_factory2

tensor([1, 2, 3], dtype=torch.int32)

In [38]:
t_factory3 = torch.from_numpy(data)
t_factory3

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [29]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [30]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [33]:
torch.rand(2,2)*10

tensor([[6.2628, 6.3048],
        [2.7812, 4.2862]])

In [39]:
data[0] = 0

In [41]:
print(t_constructor)
print(t_factory1)
print(t_factory2)
print(t_factory3)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)


In [44]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [45]:
t.size()

torch.Size([3, 4])

In [46]:
t.shape

torch.Size([3, 4])

In [47]:
len(t.shape)

2

In [48]:
torch.tensor(t.shape).prod()

tensor(12)

In [50]:
t.numel()

12

In [51]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [52]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [53]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [54]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [55]:
t.reshape(1,1,1,12)

tensor([[[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]]])

In [57]:
t.reshape(1,1,1,12).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [65]:
t.reshape(12,1).squeeze().unsqueeze(dim=1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [67]:
def flatten(t):
    t = t.reshape(-1)
    return t
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [68]:
t.sum()

tensor(24.)

In [69]:
t.prod()

tensor(1296.)

In [70]:
t.mean()

tensor(2.)

In [71]:
t.std()

tensor(0.8528)

In [72]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [73]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [74]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [77]:
t_1st_dim = t[0]
t_1st_dim

tensor([1., 1., 1., 1.])

In [78]:
t_1st_dim[0] = 0

In [79]:
t_1st_dim

tensor([0., 1., 1., 1.])

In [80]:
t

tensor([[0., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [81]:
t.argmax()

tensor(11)

In [82]:
t.max()

tensor(3.)

In [83]:
t.max(dim=1)

(tensor([1., 2., 3.]), tensor([3, 3, 3]))

In [85]:
t.mean().item()

1.9166666269302368

In [86]:
t.mean(dim=0).tolist()

[1.6666666269302368, 2.0, 2.0, 2.0]

In [87]:
t.add(2)

tensor([[2., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])

In [88]:
t.div(2)

tensor([[0.0000, 0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000, 1.5000]])

In [89]:
t + 2

tensor([[2., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])

In [90]:
np.broadcast_to(2, t.shape)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [91]:
t > 0

tensor([[0, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [97]:
t1 = torch.ones(2,2)
t1

tensor([[1., 1.],
        [1., 1.]])

In [96]:
t2 = torch.tensor([2.,4.])
t2

tensor([2., 4.])

In [103]:
print(np.broadcast_to([2,4], t1.shape))
print(np.broadcast_to([[2],[4]], t1.shape))

[[2 4]
 [2 4]]
[[2 2]
 [4 4]]


In [99]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [108]:
class Lizard:
    def __init__(self,name):
        self.name = name
        
    def set_name(self,name):
        self.name = name
        
    def get_name(self):
        return self.name
    
    def __repr__(self):
        return "Lizard Object named "+self.name

charlie = Lizard("charlie")
charlie

Lizard Object named charlie

In [109]:
charlie.set_name("Beth")
charlie

Lizard Object named Beth

In [111]:
charlie.name = "Bethany"
charlie

Lizard Object named Bethany

In [113]:
import torch.nn as nn

In [116]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv1 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
    
    def forward(self, t):
       # implement forward pass
        return t

In [118]:
network = Network()
network

Network(
  (conv1): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)